apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: job1-
spec:
  template:
    spec:
      containers:
      - name: main
        image: alpine
        command: ["echo",  "job1"]
      restartPolicy: Never
  backoffLimit: 4
